### ISSUE TITLE
Feedback for “Configuring your widget”

### ISSUE THREAD

**Issue by dijaatal** [interaxai/cdn#4]
Hey Stephen, 

Am I only allowed to embed 1 widget? I tried with 2 and once I inserted the second 1, my first widget changed to the 1st. 
![seoblog](https://github.com/interaxai/cdn/assets/134819058/10ac64ba-1f39-47eb-ae61-67630b75d0ab)
![blogideas](https://github.com/interaxai/cdn/assets/134819058/7ee3a147-90f7-42e2-9ed1-d210f8bac106)

**Comment by stephenasuncionDEV** [comment]
@Solocydev Hi, you can only add **one widget per page** with the `standard` code. Currently, if you want to add multiple widgets you must use the iframe code preset.
